model_opts:
  # argumentos para los dos generadores G1 y G2
  args:
    arch1: "deeplabv3plus"          # nombre de la arquitectura para G1
    encoder_name1: "resnet34"
    arch2: "pspnet"             # nombre de la arquitectura para G2
    encoder_name2: "resnet34"
    classification_loss: False

train_par:
  # reproducibilidad y dispositivos
  random_seed: 2024
  devices: 4
  strategy: "ddp_find_unused_parameters_true"
  profiler: False

  # ciclo de entrenamiento
  epochs: 500 #700
  batch_size: 256
  workers: 8

  # tasas de aprendizaje y regularización (G y D)
  adam_g: True
  lr_g: 0.0001 #2.5e-4 #0.00025
  lr_d: 0.0001
  weight_decay: 0.0001
  adam_betas: [0.9, 0.9]
  polynomial_power: 0.9

  # pesos en la función objetivo
  lambda_seg: 1.0
  lambda_adv: 0.01
  lambda_adv_u: 0.001
  lambda_semi: 0.1
  lambda_clas: 0.1
  lambda_clas_u: 0.1

  # semi-supervisión
  supervised_epochs: 200 #200
  gamma_thresh: 0.2 #0.8 #0.5 #0.2

  # paths y early stopping
  results_path: "/scratch/bcastane_lab/eochoaal/first_year_exam/results"
  early_stopping:
    monitor: "valid_dataset_iou"
    patience: 20
    mode: "max"

dataset:
  project: "ASSGAN" 
  experiment: "experiment"
  data_dir: "/scratch/bcastane_lab/eochoaal/first_year_exam/data/data_uncorrected"
  train: "/data/GitHub/first_year_exam/data/data_uncorrected/train.csv" #/data_uncorrected/train.csv"
  dev: "/data/GitHub/first_year_exam/data/data_uncorrected/validation.csv" #data_uncorrected/validation.csv"
  test: "/data/GitHub/first_year_exam/data/data_uncorrected/test.csv" #data_uncorrected/test.csv"
  cache_data: False
