model_opts:
  name: "attention_unet"
  args:
    inchannels: 3
    outchannels: 1
    encoder_name: "resnet34" # resnet34, mit_b1
    arch: "FPN" # FPN, Unet, Segformer
    encoder_weights: imagenet # imagenet, null
    encoder_depth: <OPTUNA_ENCODER_DEPTH>  # Optuna elegir치 entre 2 y 5

train_par:
  gpu_to_use: "cuda:0"
  random_seed: "default"
  devices: 2
  strategy: "ddp"
  profiler: False
  epochs: 50
  batch_size: 32  # Optuna elegir치 entre 8, 16, 32
  workers: 8
  lr: <OPTUNA_LR>  # Optuna optimizar치 la tasa de aprendizaje
  weight_decay: <OPTUNA_WEIGHT_DECAY>  # Optuna optimizar치 este valor
  eval_threshold: 0.5
  patience: 50
  early_stopping_flag: True
  results_path: "/data/UNET2D/results"
  optimizer:
    name: "AdamW"
  loss_opts:
    name: "DiceLossOriginal"
    args:
      weight: 0.1
      alpha: [0.0002818244106728816, 0.6997443448962491, 0.03218500222273938, 0.09628542892937603, 0.14095661371987137, 0.030546785821091195]
      gamma: 3
  num_classes: 2

dataset:
  experiment: "experiment"
  data_dir: "/data/UNET2D/512x512_maddie"
  train: "/data/UNET2D/train_maddie.csv"
  dev: "/data/UNET2D/test_maddie.csv"
  test: "/data/UNET2D/test_maddie.csv"
  cache_data: False
  rescale_factor: 128
  use_patches: False
  patch_size: 64
  patch_overlap: 0
  queue_length: 100
  samples_per_volume: 10
